# Generated by Django 4.0.2 on 2022-02-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0003_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
    ]
